title: Your Site Title
email: your-email@example.com
description: > 
  This is my awesome site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinozukamiiina.github.io/demo/" # the base hostname & protocol for your site
theme: minima
