# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   This is a description of your site.
# twitter_username: johndoe
# github_username:  johndoe

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinozukamiiina.github.io/demo/" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
